transcriberapp/urls.py
from django.urls import path
from .views import (
    RequestSummaryView,
    AskAIView,
    TranscriptionView,
    TranscriptionListView,
    TranscriptionDetailView,
    TranscriptionUpdateView,
    TranscriptionDeleteView,
    active_tasks_status,
)

app_name = "transcriberapp"

urlpatterns = [
    path("", TranscriptionView.as_view(), name="transcribe"),
    path("transcription/<int:pk>/ask_ai/", AskAIView.as_view(), name="ask_ai"),
    path("transcription/<int:pk>/summary-request/", RequestSummaryView.as_view(), name="request_summary"),
    path("transcriptions/", TranscriptionListView.as_view(), name="transcription_list"),
    path("transcriptions/<int:pk>/", TranscriptionDetailView.as_view(), name="transcription_detail"),
    path("transcriptions/<int:pk>/edit/", TranscriptionUpdateView.as_view(), name="transcription_edit"),
    path("transcriptions/<int:pk>/delete/", TranscriptionDeleteView.as_view(), name="transcription_delete"),
] + [
    path("api/transcriptions/<int:pk>/active-tasks/", active_tasks_status, name="transcription_active_tasks"),

]

yttranscriber/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("transcriberapp.urls", namespace="transcriberapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}YouTube Transcription{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    {% block extra_css %}
    <!-- additional styles -->
    {% endblock %}
</head>
<body>
    <header>
        <div class="header-container">
            <h1 class="app-title">{% block header %}YouTube Transcription Application{% endblock %}</h1>
            <nav class="simple-nav">
            <a href="{% url 'transcriberapp:transcribe' %}">Home</a>
            <a href="{% url 'transcriberapp:transcription_list' %}">Transcriptions</a>
            </nav>
        </div>
    </header>


    <main>
        {% block content %}
        <!-- specific page content -->
        {% endblock %}
    </main>

    <footer>
        <p>&copy; {{ now|default:"2025" }} - YTTranscriber</p>
    </footer>

    {% block extra_js %}
    <!-- additional JS scripts -->
    {% endblock %}
</body>
</html>